// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIxeC8ofJZcJgkf4fY8o5x5k7MEYkRuyI',
    appId: '1:77436182562:web:96378074c464189015aa7b',
    messagingSenderId: '77436182562',
    projectId: 'edugaon-4b5f2',
    authDomain: 'edugaon-4b5f2.firebaseapp.com',
    databaseURL: 'https://edugaon-4b5f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edugaon-4b5f2.appspot.com',
    measurementId: 'G-MVKXR7SL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV5BPcY2_nZIkGRPDzY4kT1Dhpkgw9RsE',
    appId: '1:77436182562:android:9abc56e0b1e03c7115aa7b',
    messagingSenderId: '77436182562',
    projectId: 'edugaon-4b5f2',
    databaseURL: 'https://edugaon-4b5f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edugaon-4b5f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABbgfEmYjb0EKrSIZFy6Y-aXBB0KoKZuA',
    appId: '1:77436182562:ios:a0dfeae10975ee1315aa7b',
    messagingSenderId: '77436182562',
    projectId: 'edugaon-4b5f2',
    databaseURL: 'https://edugaon-4b5f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edugaon-4b5f2.appspot.com',
    androidClientId: '77436182562-064q9utvrlfvpc951q09o1uos2l8bndf.apps.googleusercontent.com',
    iosClientId: '77436182562-1ph90gm6tupb1ll4ajnd831tsfifcdjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClon',
  );
}
